version: "3.8"
services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: "selenium-chrome"
    user: root
    environment:
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=4
    ports:
      - "4444:4444"
      - "7900:7900"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "2G"
    volumes:
      - /C/Temp/BrokenImages:/tmp/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium-chrome:4444"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 10s
  gradle:
    depends_on:
      - chrome
    build:
      dockerfile: Dockerfile
    container_name: "gradle"
    environment:
      - SELENIUM_HOST=${SELENIUM_HOST}
    volumes:
      - /C/Temp/BrokenImages/Artifacts:/app/artifacts/


