version: "3.8"
services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: "selenium-chrome"
    environment:
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=4
    ports:
      - "4444:4444"
      - "7900:7900"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "2G"
    volumes:
      - /C/Temp:/tmp/
